boss/urls.py
from django.urls import path, include
from boss import views

urlpatterns = [
     path('orders/<int:shop>',views.order_list, name = 'order_list'),
     path('timeinput/', views.time_input, name = "timeinput"),
     # path('api-auth/',include('rest_framework.urls', namespace='rest_framework')),
     # path('menus/<int:shop>', views.menu, name = "menu"),
     # path('order/', views.order, name = "order"),
     
]

fastcampus/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('order/',include('order.urls')),
    path('boss/',include('boss.urls')),
    path('delivery/',include('delivery.urls')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('user/',include('user.urls'))

]

order/models.py
from multiprocessing.connection import deliver_challenge
from django.db import models

# Create your models here.
class Shop(models.Model):
     shop_name = models.CharField(max_length=20)
     shop_address = models.CharField(max_length=40)
     
class Menu(models.Model):
     shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
     food_name = models.CharField(max_length=20)
     
     
class Order(models.Model):
     shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
     order_date = models.DateTimeField('date ordered')
     address = models.CharField(max_length=40)
     estimated_time = models.IntegerField(default=-1)
     deliver_finish = models.BooleanField(default=0)
     
class OrderFood(models.Model):
     order = models.ForeignKey(Order, on_delete=models.CASCADE)
     food_name = models.CharField(max_length=20)

boss/views.py
from django.shortcuts import render
from order.models import Shop, Menu, Order, OrderFood
from order.serializers import ShopSerializer, MenuSerializer
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from django.utils import timezone


@csrf_exempt
def order_list(request, shop):
     if request.method == 'GET':
          order_list = Order.objects.filter(shop = shop)
          return render(request,'boss/order_list.html', {'order_list':order_list})
     else:
          return HttpResponse(status=404)

@csrf_exempt
def  time_input(request):
     if request.method == 'POST':
          order_item = Order.objects.get(pk=int(request.POST['order_id']))
          shop = order_item.shop.id
          order_item.estimated_time = int(request.POST['estimated_time'])
          order_item.save()
          return render(request, 'boss/success.html',{'shop':int(shop)})
     else:
          return HttpResponse(status=404)

boss/templates/boss/order_list.html
<table style="border: 1px solid black">
  <tr style="border: 1px solid black">
    <th style="border: 1px solid black">주문시간</th>
    <th style="border: 1px solid black">음식</th>
    <th style="border: 1px solid black">배달 예상 시간</th>
    <th style="border: 1px solid black">배달 완료 여부</th>
  </tr>
  {% for order in order_list %}
  <tr style="border: 1px solid black">
    <td style="border: 1px solid black">{{order.order_date}}</td>
    <td style="border: 1px solid black">
      {% for food in order.orderfood_set.all %}
      <h5>{{food.food_name}}</h5>
      {%endfor%}
    </td>
    <td style="border: 1px solid black">
      {% if order.estimated_time == -1 %}
      <form method="POST" action="{% url 'timeinput' %}">
        <input type="number" name="estimated_time" />
        <input type="hidden" name="order_id" value="{{order.id}}" />
        <input type="submit" value="예상시간 출력" />
      </form>
      {% else %} {{order.estimated_time}}분{%endif%}
    </td>
    <td style="border: 1px solid black">
      {% if order.deliver_finish == 0 %} 배송중 {% else %} 완료 {%endif%}
    </td>
  </tr>
  {% endfor%}
</table>

boss/templates/boss/success.html
예상 시간 입력을 완료하였습니다. 다른 주문 내역을 보기 위해선
<a href="/boss/orders/{{shop}}">여기</a>를 클릭해주세요.